--update pelicula  set pel_anio="2012" where pel_titulo="El señor de los anillos";
--update usuario  set usu_celular="3115678432"  where alias="ninja";
--delete from transmision  where ptransmisiones="Stardust" and alias="green";