-- MySQL Script generated by MySQL Workbench
-- dom 29 ago 2021 11:28:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FantasiPlus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema FantasiPlus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `FantasiPlus` DEFAULT CHARACTER SET utf8 ;
USE `FantasiPlus` ;

-- -----------------------------------------------------
-- Table `FantasiPlus`.`Contenido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FantasiPlus`.`Contenido` (
  `id_contenido` INT NOT NULL,
  `n_contenido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_contenido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FantasiPlus`.`Series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FantasiPlus`.`Series` (
  `id_serie` INT NOT NULL,
  `s_titulo` VARCHAR(45) NOT NULL,
  `s_nTemporada` INT NOT NULL,
  `s_nEpisodios` INT NOT NULL,
  `id_contenido` INT NOT NULL,
  PRIMARY KEY (`id_serie`),
  INDEX `id_contenido_fk_idx` (`id_contenido` ASC) VISIBLE,
  CONSTRAINT `id_contenidofk`
    FOREIGN KEY (`id_contenido`)
    REFERENCES `FantasiPlus`.`Contenido` (`id_contenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FantasiPlus`.`Director`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FantasiPlus`.`Director` (
  `dir_id` INT NOT NULL,
  `dir_nombre` VARCHAR(45) NOT NULL,
  `dir_apellido` VARCHAR(45) NOT NULL,
  `dir_nacionalidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dir_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FantasiPlus`.`Pelicula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FantasiPlus`.`Pelicula` (
  `id_pelicula` INT NOT NULL,
  `p_titulo` VARCHAR(45) NOT NULL,
  `p_resumen` VARCHAR(45) NULL,
  `p_anio` DATETIME NOT NULL,
  `dir_id` INT NOT NULL,
  `id_contenido` INT NOT NULL,
  PRIMARY KEY (`id_pelicula`),
  INDEX `dir_id_idx` (`dir_id` ASC) VISIBLE,
  INDEX `id_contenido_fk_idx` (`id_contenido` ASC) VISIBLE,
  CONSTRAINT `dir_id`
    FOREIGN KEY (`dir_id`)
    REFERENCES `FantasiPlus`.`Director` (`dir_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_contenido_fk`
    FOREIGN KEY (`id_contenido`)
    REFERENCES `FantasiPlus`.`Contenido` (`id_contenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FantasiPlus`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FantasiPlus`.`Usuarios` (
  `u_alias` VARCHAR(45) NOT NULL,
  `u_nombre` VARCHAR(45) NOT NULL,
  `u_apellido` VARCHAR(45) NOT NULL,
  `u_email` VARCHAR(45) NOT NULL,
  `u_celular` BIGINT(10) NULL,
  `u_contraseña` VARCHAR(45) NOT NULL,
  `u_fechaNacimiento` DATE NOT NULL,
  PRIMARY KEY (`u_alias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FantasiPlus`.`Transmision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FantasiPlus`.`Transmision` (
  `t_date` DATE NOT NULL,
  `t_hora` VARCHAR(45) NOT NULL,
  `id_pelicula` INT NOT NULL,
  `u_alias` VARCHAR(45) NOT NULL,
  `id_contenido` INT NOT NULL,
  INDEX `fk_u_alias_idx` (`u_alias` ASC) VISIBLE,
  PRIMARY KEY (`id_pelicula`),
  INDEX `id_contenido_fk_idx` (`id_contenido` ASC) VISIBLE,
  CONSTRAINT `u_alias_fk`
    FOREIGN KEY (`u_alias`)
    REFERENCES `FantasiPlus`.`Usuarios` (`u_alias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idcontenido_fk`
    FOREIGN KEY (`id_contenido`)
    REFERENCES `FantasiPlus`.`Contenido` (`id_contenido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
